import { ProjectTemplate } from '../types/project';

export const projectTemplates: ProjectTemplate[] = [
  {
    id: 'website-complete',
    name: 'Complete Website',
    description: 'Mirror an entire website with all assets',
    category: 'website',
    icon: 'Globe',
    basicOptions: {
      mirrorDepth: 'deep',
      followExternal: false,
      getImages: true,
      getVideos: true,
      getAudio: true,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 100 * 1024 * 1024,
      maxDownloadSize: 5 * 1024 * 1024 * 1024,
      connectionTimeout: 30,
      retries: 3,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: true,
      logLevel: 'normal',
      updateExisting: false,
    },
  },
  {
    id: 'documentation',
    name: 'Documentation Site',
    description: 'Archive documentation with fast navigation',
    category: 'documentation',
    icon: 'BookOpen',
    basicOptions: {
      mirrorDepth: 'unlimited',
      followExternal: false,
      getImages: true,
      getVideos: false,
      getAudio: false,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 50 * 1024 * 1024,
      maxDownloadSize: 2 * 1024 * 1024 * 1024,
      connectionTimeout: 30,
      retries: 3,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: true,
      hideQueryStrings: true,
      logLevel: 'normal',
    },
  },
  {
    id: 'media-gallery',
    name: 'Media Gallery',
    description: 'Download images, videos, and media files',
    category: 'media',
    icon: 'Image',
    basicOptions: {
      mirrorDepth: 'medium',
      followExternal: false,
      getImages: true,
      getVideos: true,
      getAudio: true,
      getDocuments: false,
      respectRobotsTxt: true,
      maxFileSize: 500 * 1024 * 1024,
      maxDownloadSize: 20 * 1024 * 1024 * 1024,
      connectionTimeout: 60,
      retries: 5,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: false,
      logLevel: 'normal',
    },
  },
  {
    id: 'blog-archive',
    name: 'Blog Archive',
    description: 'Archive blog posts with comments and images',
    category: 'blog',
    icon: 'FileText',
    basicOptions: {
      mirrorDepth: 'deep',
      followExternal: false,
      getImages: true,
      getVideos: false,
      getAudio: false,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 50 * 1024 * 1024,
      maxDownloadSize: 3 * 1024 * 1024 * 1024,
      connectionTimeout: 30,
      retries: 3,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: true,
      hideQueryStrings: false,
      logLevel: 'normal',
    },
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Catalog',
    description: 'Archive product pages and images',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    basicOptions: {
      mirrorDepth: 'medium',
      followExternal: false,
      getImages: true,
      getVideos: true,
      getAudio: false,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 100 * 1024 * 1024,
      maxDownloadSize: 10 * 1024 * 1024 * 1024,
      connectionTimeout: 45,
      retries: 4,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: true,
      hideQueryStrings: true,
      logLevel: 'verbose',
    },
  },
  {
    id: 'quick-single',
    name: 'Single Page',
    description: 'Download just one page with its assets',
    category: 'custom',
    icon: 'File',
    basicOptions: {
      mirrorDepth: 'page-only',
      followExternal: false,
      getImages: true,
      getVideos: true,
      getAudio: true,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 100 * 1024 * 1024,
      maxDownloadSize: 1 * 1024 * 1024 * 1024,
      connectionTimeout: 30,
      retries: 2,
    },
    advancedOptions: {
      parseLinks: false,
      keepStructure: false,
      logLevel: 'normal',
    },
  },
  {
    id: 'custom',
    name: 'Custom Configuration',
    description: 'Start with default settings and customize',
    category: 'custom',
    icon: 'Settings',
    basicOptions: {
      mirrorDepth: 'medium',
      followExternal: false,
      getImages: true,
      getVideos: true,
      getAudio: true,
      getDocuments: true,
      respectRobotsTxt: true,
      maxFileSize: 100 * 1024 * 1024,
      maxDownloadSize: 5 * 1024 * 1024 * 1024,
      connectionTimeout: 30,
      retries: 3,
    },
    advancedOptions: {
      parseLinks: true,
      keepStructure: true,
      logLevel: 'normal',
    },
  },
];

export function getTemplateById(id: string): ProjectTemplate | undefined {
  return projectTemplates.find((template) => template.id === id);
}

export function getTemplatesByCategory(category: string): ProjectTemplate[] {
  if (category === 'all') return projectTemplates;
  return projectTemplates.filter((template) => template.category === category);
}
